import { useParams } from "react-router-dom"
import { ProductGallery } from "../components"


const Categories = () => {
    const category = useParams().category
    const productos = [
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
        {
            "clotheType": "shirt",
            "brand": "adidas",
            "name": "camiseton",
            "gender": "x",
            "sport": "running",
            "collection": "primavera",
            "color": "darkred",
            "size": "xxl",
            "image": 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2c6ff231fe04a809820aec4010a2b1d_9366/Jersey_Visitante_Seleccion_Nacional_de_Mexico_Beige_HD9314_21_model.jpg',
            "stock": "10",
            "price": "13000",
            "promotion": "0.15"
        },
    ]

    return (
        <main className="mb-10 mt-24">
            <h1 className="text-3xl uppercase font-bold">{category}</h1>
            <ProductGallery productos={productos} />
        </main>
    )
}

export default Categories