export { default as Home } from './Home'
export { default as Details } from './Details'
export { default as Categories } from './Categories'
export { default as DashCategories } from './DashCategory'
export { Profile2 } from './Profile2'
